name: BUG 反馈 | Bug Report
description: issue模板
title: "(在这里给issue命名 | Name the issue here)"
body:
- type: dropdown
  id: type
  attributes:
    label: 反馈类型
    multiple: true
    options:
      - 程序错误 | BUG
  validations:
    required: true
- type: textarea
  id: system_report
  attributes:
    label: MCSL2 系统报告 | MCSL2 System Report
    description: 
      - 你可以在“设置”页获取系统报告。
      - You can obtain the system report on the Settings page.
      - 如果你所用的MCSL2版本不支持系统报告，请按以下格式填写：
      - ---NO SYSTEM REPORT---
      - System: Windows/macOS/Linux x64/x86/arm/arm64
      - MCSL2: v2.1.4.0 (For example)
      - PyQt5: v5.19.9 (For example) (Optional)
  validations:
    required: true
- type: dropdown
  id: aspects
  attributes:
    label: 你在哪方面遇到了问题？ | Where are you having problems?
    multiple: true
    options:
      - MCSL2主页 | MCSL2's Home Page
      - MCSL2启动服务器 | Using MCSL2 to run a Minecraft server
      - MCSL2新建服务器 | Using MCSL2 to configure a new Minecraft server
      - MCSL2下载 | Using MCSL2's download functions
      - MCSL2终端 | Using MCSL2's Minecraft server console
      - MCSL2插件 | Configuring MCSL2's plugins system
      - MCSL2设置 | Setting MCSL2
      - 启动/关闭MCSL2 | Start/Close MCSL2
      - MCSL2更新 | Updating MCSL2
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: 说明 | Description
    description: 
      - 说明你的问题、麻烦、建议等。
      - Explain your problem, trouble, suggestion, etc.
  validations:
    required: true
- type: checkboxes
  id: check
  attributes:
    label: 确认 | Confirm
    description: 
      - 请翻阅[Issues](https://github.com/MCSLTeam/MCSL2/issues)中是否有与你的Issue重复的项。
      - Please read [Issues](https://github.com/MCSLTeam/MCSL2/issues) to see if there is the Issue of duplicate items with you.
    options:
      - label: 我确保我的Issue没有和别人的重复 | I make sure my Issue is not the same as someone else's
        required: true
- type: textarea
id: "attachment"
attributes:
  label: 附件(可选) | Attachment (Optional)
  placeholder: "先点击这个文本框，然后再将文件直接拖拽到文本框中以上传。\nClick on the text box and then drag the file directly into the text box to upload."
validations:
  required: false
