name: "BUG 反馈"
description: "issue模板"
title: "BUG | (在这里给issue命名"
body:

- type: textarea
  id: system_report
  attributes:
    label: "MCSL2 系统报告"
    description: "你可以在“设置”页获取系统报告。"
  validations:
    required: true

- type: dropdown
  id: aspects
  attributes:
    label: "你在哪方面遇到了问题？"
    multiple: true
    options:
      - "MCSL2主页"
      - "MCSL2启动服务器"
      - "MCSL2新建服务器"
      - "MCSL2下载"
      - "MCSL2终端"
      - "MCSL2插件"
      - "MCSL2设置"
      - "启动/关闭MCSL2"
      - "MCSL2更新"
  validations:
    required: true

- type: textarea
  id: description
  attributes:
    label: "说明"
    description: "说明你的问题、麻烦、建议等。"
  validations:
    required: true

- type: checkboxes
  id: check
  attributes:
    label: "确认"
    description: "请翻阅[Issues](https://github.com/MCSLTeam/MCSL2/issues)中是否有与你的Issue重复的项。"
    options:
      - label: "我确保我的Issue没有和别人的重复"
        required: true

- type: textarea
  id: "attachment"
  attributes:
    label: "附件(可选)"
    placeholder: "先点击这个文本框，然后再将文件直接拖拽到文本框中以上传。"