#     Copyright 2024, MCSL Team, mailto:services@mcsl.com.cn
#
#     Part of "MCSL2", a simple and multifunctional Minecraft server launcher.
#
#     Licensed under the GNU General Public License, Version 3.0, with our
#     additional agreements. (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#        https://github.com/MCSLTeam/MCSL2/raw/master/LICENSE
#
################################################################################
name: Windows Debug Build

on: workflow_dispatch

jobs:
  Windows:
    runs-on: windows-2019
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
          cache-dependency-path: |
            requirement.txt

      - name: Dependencies
        shell: pwsh
        run: |
          python -m pip install tomli
          python Tools/gen-requirements.py
          python -m pip install --upgrade pip
          python -m pip install -U -r requirements.txt
          python -m pip uninstall numpy -y
          python -m pip uninstall scipy -y

      - name: Build
        run: |
          python -m lndl_nuitka . -y

      - name: Optimize
        shell: pwsh
        run: |
          Remove-Item -Force -Recurse .\build\MCSL2.dist\zstandard
          Remove-Item -Force -Recurse .\build\MCSL2.dist\_asyncio.pyd
          Remove-Item -Force -Recurse .\build\MCSL2.dist\pyexpat.pyd
          Remove-Item -Force -Recurse .\build\MCSL2.dist\qt5qml.dll
          Remove-Item -Force -Recurse .\build\MCSL2.dist\qt5qmlmodels.dll
          Remove-Item -Force -Recurse .\build\MCSL2.dist\qt5quick.dll
          .\upx.exe -9 build/MCSL2.dist/_ctypes.pyd build/MCSL2.dist/_decimal.pyd build/MCSL2.dist/_elementtree.pyd build/MCSL2.dist/_lzma.pyd build/MCSL2.dist/_overlapped.pyd build/MCSL2.dist/_socket.pyd build/MCSL2.dist/_ssl.pyd build/MCSL2.dist/_win32sysloader.pyd build/MCSL2.dist/libffi-7.dll build/MCSL2.dist/libcrypto-1_1.dll build/MCSL2.dist/libssl-1_1.dll build/MCSL2.dist/MCSL2.exe build/MCSL2.dist/python38.dll build/MCSL2.dist/pythoncom38.dll build/MCSL2.dist/pywintypes38.dll build/MCSL2.dist/qt5core.dll build/MCSL2.dist/qt5dbus.dll build/MCSL2.dist/qt5gui.dll build/MCSL2.dist/qt5multimedia.dll build/MCSL2.dist/qt5network.dll build/MCSL2.dist/qt5printsupport.dll build/MCSL2.dist/qt5svg.dll build/MCSL2.dist/qt5websockets.dll build/MCSL2.dist/qt5widgets.dll build/MCSL2.dist/qt5xml.dll build/MCSL2.dist/select.pyd build/MCSL2.dist/unicodedata.pyd build/MCSL2.dist/win32api.pyd build/MCSL2.dist/win32gui.pyd build/MCSL2.dist/win32print.pyd

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MCSL2-Windows-x64
          path: |
            build/MCSL2.dist/**/*
